// Presentation recipes: keep data/hooks in the view; edit only tw: classes here.
export default {
  "panel": "tw:fixed tw:[inset:0_0_0_auto] tw:[z-index:1040] tw:flex tw:flex-col tw:[width:min(600px,_100vw)] tw:[height:100dvh] tw:bg-surface tw:[border-left:1px_solid_var(--color-qms-border)] tw:[box-shadow:-8px_0_32px_#21263114] tw:text-foreground",
  "expanded": "tw:w-full",
  "header": "tw:sticky tw:top-0 tw:[z-index:10] tw:shrink-0 tw:bg-white tw:[border-bottom:1px_solid_var(--color-qms-border)]",
  "headerRow": "tw:flex tw:items-center tw:gap-2 tw:min-h-11 tw:[padding:6px_12px] tw:[&_button]:[display:inline-flex] tw:[&_button]:items-center tw:[&_button]:justify-center tw:[&_button]:gap-1 tw:[&_button]:min-h-7 tw:[&_button]:min-w-7 tw:[&_button]:shrink-0 tw:[&_button]:px-1.5 tw:max-[576px]:[padding:6px_8px] tw:max-[576px]:gap-1.5",
  "backButton": "tw:whitespace-nowrap tw:[font-size:13px] tw:max-[576px]:[&_span]:hidden",
  "headerIdentity": "tw:flex-1 tw:min-w-0 tw:flex tw:items-baseline tw:gap-2",
  "headerFolio": "tw:shrink-0 tw:m-0 tw:text-sm tw:[line-height:1.2] tw:font-bold",
  "headerCliente": "tw:min-w-0 tw:text-muted tw:[font-size:13px] tw:whitespace-nowrap tw:overflow-hidden tw:text-ellipsis tw:max-[576px]:hidden",
  "headerBadges": "tw:flex tw:items-center tw:gap-1 tw:shrink-0 tw:[max-width:42%] tw:overflow-hidden tw:[&_[data-slot='badge']]:block tw:[&_[data-slot='badge']]:overflow-hidden tw:[&_[data-slot='badge']]:text-ellipsis tw:[&_[data-slot='badge']]:whitespace-nowrap tw:[&_[data-slot='badge']]:[padding-block:2px] tw:max-[576px]:[max-width:50%]",
  "headerActions": "tw:flex tw:[gap:2px] tw:shrink-0",
  "tabs": "tw:[padding:0_12px] tw:gap-4.5 tw:shrink-0 tw:[&_button]:flex tw:[&_button]:items-center tw:[&_button]:gap-1.5 tw:[&_button]:[padding:5px_0_6px] tw:[&_button]:[font-size:13px] tw:[&_button]:text-muted tw:[&_button]:font-medium tw:[&_button]:[border-radius:0] tw:[&_button]:whitespace-nowrap tw:[&_button[aria-current='page']]:text-primary tw:max-[576px]:[padding:0_12px] tw:max-[576px]:gap-4",
  "body": "tw:flex-1 tw:min-h-0 tw:overflow-y-auto tw:overscroll-contain tw:[padding:16px_14px_28px] tw:[background:#f3f4f6] tw:select-text tw:max-[576px]:[padding:12px_10px_20px]",
  "page": "tw:[max-width:720px] tw:mx-auto tw:[padding:20px_22px] tw:bg-white tw:rounded-lg tw:[box-shadow:0_4px_15px_rgba(0,_0,_0,_0.05)] tw:max-[576px]:p-4",
  "block": "tw:[padding:14px_0] tw:[border-bottom:1px_solid_#eef0f4] tw:[&:first-child]:pt-0 tw:[&:last-child]:[border-bottom:0] tw:[&:last-child]:pb-0",
  "blockTitle": "tw:[margin:0_0_8px] tw:[font-size:11px] tw:[line-height:1.4] tw:font-semibold tw:[letter-spacing:0.06em] tw:uppercase tw:text-muted",
  "blockActions": "tw:flex tw:justify-end tw:gap-2 tw:[margin-top:10px]",
  "prose": "tw:m-0 tw:text-foreground tw:[font-size:15px] tw:[line-height:1.7] tw:whitespace-pre-wrap tw:[overflow-wrap:anywhere]",
  "proseEmpty": "tw:m-0 tw:text-muted tw:text-sm tw:italic",
  "metadata": "tw:grid tw:[grid-template-columns:repeat(2,_minmax(0,_1fr))] tw:[gap:12px_24px] tw:m-0 tw:[&_dt]:[font-size:11px] tw:[&_dt]:[line-height:1.4] tw:[&_dt]:font-semibold tw:[&_dt]:[letter-spacing:0.06em] tw:[&_dt]:uppercase tw:[&_dt]:text-muted tw:[&_dd]:[margin:4px_0_0] tw:[&_dd]:[font-size:15px] tw:[&_dd]:font-medium tw:[&_dd]:[overflow-wrap:anywhere] tw:max-[576px]:[grid-template-columns:minmax(0,_1fr)]",
  "metadataWide": "tw:[grid-column:1_/_-1]",
  "content": "tw:w-full tw:[max-width:960px] tw:mx-auto tw:grid tw:gap-5",
  "section": "tw:p-5 tw:m-0 tw:[border-color:var(--color-qms-border)] tw:[box-shadow:none] tw:[&_h2]:[margin:0_0_12px] tw:[&_h2]:text-base tw:[&_h2]:[line-height:1.5] tw:[&_h2]:font-semibold tw:[&_h2]:[letter-spacing:normal] tw:[&_h2]:normal-case tw:[&_h2]:text-foreground tw:[&_p]:[line-height:1.65] tw:[&_button]:[display:inline-flex] tw:[&_button]:items-center tw:[&_button]:justify-center tw:[&_button]:gap-2 tw:[&_svg]:w-4.5 tw:[&_svg]:h-4.5 tw:[&:is(input,textarea)]:text-base",
  "sectionIntro": "tw:[&_h2]:text-xl tw:[&_h2]:font-semibold tw:[&_h2]:[margin:0_0_6px] tw:[&_p]:text-muted tw:[&_p]:m-0",
  "empty": "tw:[padding:24px_12px] tw:m-0 tw:text-center tw:text-muted tw:bg-background tw:rounded-md",
  "timeline": "tw:grid tw:gap-4",
  "timelineItem": "tw:flex tw:gap-3",
  "timelineIcon": "tw:grid tw:[place-items:center] tw:shrink-0 tw:w-8 tw:h-8 tw:[border-radius:50%] tw:[background:var(--color-qms-primary-subtle)] tw:text-primary",
  "timelineContent": "tw:min-w-0 tw:flex-1 tw:pb-4 tw:[border-bottom:1px_solid_var(--color-qms-border)] tw:[&_p]:[margin:8px_0_0] tw:[&_p]:[overflow-wrap:anywhere]",
  "timelineMeta": "tw:flex tw:justify-between tw:flex-wrap tw:[gap:4px_12px] tw:text-sm tw:text-muted",
  "markdown": "tw:p-5 tw:[line-height:1.7] tw:[overflow-wrap:anywhere] tw:[&:is(h1,h2,h3)]:[margin:20px_0_12px] tw:[&:is(h1,h2,h3)]:text-lg tw:[&:is(h1,h2,h3)]:font-semibold tw:[&:is(ul,ol)]:pl-6 tw:[&_li]:mb-1.5"
} as const
