// Presentation recipes: keep data/hooks in the view; edit only tw: classes here.
export default {
  "page": "tw:min-h-full",
  "layout": "tw:grid tw:[grid-template-columns:230px_minmax(0,_1fr)] tw:gap-6 tw:items-start tw:max-[1200px]:[grid-template-columns:190px_minmax(0,1fr)] tw:max-[1200px]:gap-4 tw:max-[992px]:[grid-template-columns:1fr]",
  "navigation": "tw:p-3 tw:sticky tw:top-0 tw:[&_nav]:flex-col tw:[&_nav]:gap-1 tw:[&_button]:flex tw:[&_button]:items-center tw:[&_button]:gap-3 tw:[&_button]:w-full tw:[&_button]:p-3 tw:[&_button]:text-left tw:[&_button]:text-foreground tw:[&_button]:[font-size:15px] tw:[&_button]:[border:0] tw:[&_button]:rounded-md tw:[&_button:hover]:bg-background tw:[&_button[aria-current='page']]:[background:var(--color-qms-primary-subtle)] tw:[&_button[aria-current='page']]:text-primary tw:[&_button[aria-current='page']]:font-semibold tw:max-[992px]:[position:static] tw:max-[992px]:[&_nav]:flex-row tw:max-[992px]:[&_nav]:flex-nowrap tw:max-[992px]:[&_nav]:[overflow-x:auto] tw:max-[992px]:[&_button]:[width:auto] tw:max-[992px]:[&_button]:shrink-0 tw:max-[576px]:[&_button]:[padding:10px] tw:max-[576px]:[&_button]:text-sm tw:max-[576px]:[&_button]:gap-2",
  "navTitle": "tw:[margin:4px_12px_12px] tw:[font-size:12px] tw:[line-height:1.5] tw:font-semibold tw:[letter-spacing:.08em] tw:uppercase tw:text-muted tw:max-[992px]:hidden",
  "content": "tw:min-w-0",
  "sectionHeader": "tw:flex tw:justify-start tw:flex-nowrap tw:gap-3.5 tw:items-center tw:p-6 tw:bg-surface tw:[&_h2]:text-xl tw:[&_h2]:[line-height:1.4] tw:[&_h2]:[margin:0_0_4px] tw:[&_h2]:font-semibold tw:[&_p]:text-sm tw:[&_p]:m-0 tw:[&_p]:text-muted tw:[&_p]:[line-height:1.6] tw:max-[1200px]:p-5 tw:max-[576px]:p-4",
  "sectionIcon": "tw:grid tw:[place-items:center] tw:shrink-0 tw:w-11 tw:h-11 tw:[background:var(--color-qms-primary-subtle)] tw:text-primary tw:rounded-lg",
  "sectionBody": "tw:p-6 tw:min-w-0 tw:[&_table]:mb-0 tw:[&_table_:is(th,td)]:[vertical-align:middle] tw:[&_table_:is(th,td)]:[padding:14px_16px] tw:[&_button]:[display:inline-flex] tw:[&_button]:items-center tw:[&_button]:justify-center tw:[&_button]:gap-2 tw:[&_button]:[min-height:36px] tw:[&_button]:whitespace-nowrap tw:[&_button_svg]:w-4.5 tw:[&_button_svg]:h-4.5 tw:[&:is(input,textarea)]:min-w-0 tw:[&_select]:min-w-0 tw:[&_[data-slot='table-scroll']]:[border:1px_solid_var(--color-qms-border)] tw:[&_[data-slot='table-scroll']]:rounded-md tw:max-[1200px]:p-5 tw:max-[576px]:p-4",
  "filters": "tw:grid tw:[grid-template-columns:minmax(0,_1fr)_minmax(0,_1.5fr)_auto] tw:[align-items:end] tw:gap-4 tw:[&_label]:block tw:[&_label]:text-sm tw:[&_label]:mb-2 tw:[&_label]:text-muted tw:max-[1200px]:[grid-template-columns:1fr_1fr] tw:max-[1200px]:[&_>_:last-child]:[justify-self:start] tw:max-[576px]:[grid-template-columns:1fr]",
  "editor": "tw:grid tw:[grid-template-columns:minmax(160px,2fr)_minmax(120px,1fr)_minmax(90px,.7fr)] tw:gap-4 tw:[align-items:end] tw:bg-background tw:p-5 tw:[border:1px_solid_var(--color-qms-border)] tw:rounded-md tw:[&_label]:mb-2 tw:[&_label]:text-sm tw:max-[576px]:[grid-template-columns:1fr]",
  "editorActions": "tw:flex tw:items-center tw:gap-3 tw:[grid-column:1_/_-1]",
  "toolbar": "tw:flex tw:items-center tw:justify-between tw:gap-4 tw:flex-wrap tw:[&_p]:flex-1 tw:[&_p]:[min-width:220px] tw:[&_p]:m-0"
} as const
