import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { build } from 'esbuild';
const root=process.cwd(),out=path.join(root,'.performance/dashboard-preview');
fs.mkdirSync(out,{recursive:true});
const mocks=`
const mode=new URLSearchParams(location.search).get('scenario');
const empty=mode==='empty', fail=mode==='error';
const now=new Date();const date=(d)=>new Date(now.getFullYear(),now.getMonth(),now.getDate()+d).toISOString();
const result=(data)=>({data:fail?undefined:data,isPending:false,isFetching:false,error:fail?new Error('No se pudo conectar con el servicio de datos'):null,refetch:()=>{}});
const rows=empty?[]:Array.from({length:8},(_,i)=>({id:String(i),folio:'QUEJA-2026-00'+(i+1),cliente_nombre:'Organización de prueba '+(i+1),estado:['Recibido','En Investigación','Pendiente de Revisión GC','Resuelto'][i%4],fecha:date(-30),fecha_sla:i===7?null:date(i-3),prioridad:'Alta'}));
const series=Array.from({length:now.getMonth()+1},(_,i)=>({mes:new Date(now.getFullYear(),i,1).toLocaleDateString('es-CR',{month:'short'}).replace('.',''),recibidas:empty?0:[3,5,0,8,4,10,12,8,9,15,11,17][i],resueltas:empty?0:[0,2,0,4,2,6,9,7,5,10,8,12][i]}));
export const useZonaHoraria=()=>({data:'America/Costa_Rica',isPending:false,isFetching:false,error:null,refetch:()=>{}});export const quejasAnalisisKey=['quejas','analisis'],quejasEstadisticasKey=['quejas','stats'];
export const generalTotalesKey=['dashboard','totales'];
export const useGeneralTotales=(modulos)=>result(modulos.map(m=>({id:m.id,total:empty?0:({quejas:54,sacp:31,documentos:25,riesgos:18,auditorias:12,procesos:9,revision:7})[m.id]})));
export const useQuejasAnalisis=()=>result({anio:now.getFullYear(),series,porEstado:empty?[]:[{etiqueta:'Recibido',total:12},{etiqueta:'En Investigación',total:8},{etiqueta:'Pendiente de Revisión GC',total:3},{etiqueta:'Resuelto',total:5},{etiqueta:'Finalizado',total:14},{etiqueta:'No Procede',total:2}],porCategoria:empty?[]:[{etiqueta:'Queja',total:24},{etiqueta:'Denuncia',total:6},{etiqueta:'Sugerencia',total:9},{etiqueta:'Felicitación',total:5}],activas:rows,atencion:rows});
export const useQuejasEstadisticas=()=>result({total:empty?0:54,mesActual:empty?0:8,totalConDecision:empty?0:30,procedentes:empty?0:28,pctProcedencia:empty?0:93});
export const useDashboard=()=>result({indicadores:[{valor:empty?0:28},{valor:empty?0:13},{valor:empty?0:6},{valor:empty?0:4}],tareas:rows.map((r,i)=>({id:r.id,titulo:r.folio,tipo:i%2?'Correctiva':'Queja',entidad:i%2?'SACP':'Quejas',vence:r.fecha_sla,estado:r.estado,prioridad:r.prioridad}))});
export const useActividadReciente=()=>result(empty?[]:[{id:'1',descripcion:'Se asignó una queja para investigación.',created_at:date(0)},{id:'2',descripcion:'Se registró una resolución.',created_at:date(-1)}]);
const sacp=empty?[]:Array.from({length:12},(_,i)=>({id:'s'+i,folio:'SACP-2026-00'+i,tipo:i%3?'Correctiva':'Preventiva',descripcion:'Acción de prueba',estado:['Abierta','En Proceso','En Validación','Cerrada'][i%4],prioridad:'Alta',fecha_apertura:new Date(now.getFullYear(),i%9,10).toISOString(),fecha_limite:date(i-4)}));
const docs=empty?[]:Array.from({length:12},(_,i)=>({id:'d'+i,codigo_doc:'DOC-'+i,titulo:'Documento de prueba '+i,version_actual:'1.0',estado:['Publicado','Borrador','En Revisión'][i%3],categoria:'Procedimiento',created_at:new Date(now.getFullYear(),i%9,10).toISOString()}));
const versiones=empty?[]:Array.from({length:now.getMonth()+1},(_,i)=>({mes:new Date(now.getFullYear(),i,1).toLocaleDateString('es-CR',{month:'short'}).replace('.',''),total:[2,1,3,0,4,3,2,5,3][i]||0}));
const riesgos=empty?[]:Array.from({length:12},(_,i)=>({id:'r'+i,folio:'RIESGO-2026-00'+i,descripcion:'Riesgo de prueba '+i,categoria:'Operación',nivel:['Crítico','Alto','Medio','Bajo'][i%4],estado:['Activo','En tratamiento','Mitigado'][i%3],probabilidad:3,impacto:2,fecha_identificacion:new Date(now.getFullYear(),i%9,10).toISOString()}));
export const useSacpAnalisis=()=>result(sacp),useDocumentosAnalisis=()=>result(docs),useVersionesAnalisis=()=>result(versiones),useRiesgosAnalisis=()=>result(riesgos);
`;
await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import Dashboard from '@/app/page';createRoot(document.getElementById('root')).render(<div className="coreui-scope p-4"><p>Vista de prueba: <a href="/">Con datos</a> | <a href="/?scenario=empty">Sin datos</a> | <a href="/?scenario=error">Error de consulta</a></p><Dashboard/></div>);`,loader:'tsx',resolveDir:root},bundle:true,format:'esm',jsx:'automatic',outfile:path.join(out,'bundle.js'),define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'preview',setup(b){
b.onResolve({filter:/^@\/lib\/queries\/use(Dashboard|Quejas|QuejasAnalisis|ModulosAnalisis|ZonaHoraria|GeneralTotales)$/},()=>({path:'fixtures',namespace:'fixture'}));
b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:mocks,loader:'js'}));
b.onResolve({filter:/^@\/lib\/store\/auth-store$/},()=>({path:'auth',namespace:'stub'}));
b.onResolve({filter:/^@tanstack\/react-query$/},()=>({path:'query',namespace:'stub'}));
b.onResolve({filter:/^@\/hooks\/useRealtimeSubscription$/},()=>({path:'realtime',namespace:'stub'}));
b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'stub'}));
b.onResolve({filter:/^next\/dynamic$/},()=>({path:'dynamic',namespace:'stub'}));
b.onLoad({filter:/.*/,namespace:'stub'},a=>({loader:'tsx',resolveDir:root,contents:a.path==='realtime'?'export const useRealtimeSubscription=()=>{}':a.path==='auth'?`export const useAuthStore=(select)=>select({user:{rol:'admin'},permisos:['quejas','sacp','documentos','riesgos','auditorias','procesos','revision'].map(modulo=>({modulo,leer:true,escribir:true}))});`:a.path==='query'?`export const useIsFetching=()=>0;export const useQueryClient=()=>({invalidateQueries:()=>Promise.resolve()});`:a.path==='link'?`import React from 'react';export default function Link(p){return <a {...p}/>} `:`import React,{lazy,Suspense} from 'react';export default function dynamic(load,opts){const C=lazy(()=>load().then(defaultExport=>({default:defaultExport})));return p=><Suspense fallback={opts.loading?.()}><C {...p}/></Suspense>}`}));
}}]});
http.createServer((req,res)=>{
const name=req.url.split('?')[0];
const file=name==='/global.css'?path.join(root,'.performance/smoke/global.css'):['/bundle.js','/bundle.css'].includes(name)?path.join(out,name.slice(1)):null;
res.setHeader('Content-Type',file?file.endsWith('.css')?'text/css':'text/javascript':'text/html; charset=utf-8');
res.end(file?fs.readFileSync(file):'<!doctype html><html lang="es"><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"><title>Dashboard CoreUI - prueba aislada</title><link rel="stylesheet" href="/global.css"><link rel="stylesheet" href="/bundle.css"><div id="root"></div><script type="module" src="/bundle.js"></script></html>');
}).listen(3104,'127.0.0.1',()=>console.log('Vista de prueba: http://127.0.0.1:3104'));
